# Generated by Django 5.1.3 on 2024-12-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlfaTrader_App', '0003_transactions_transaction_type_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange', models.CharField(max_length=10)),
            ],
        ),
    ]
