# Generated by Django 5.1.3 on 2024-12-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlfaTrader_App', '0004_stocks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocks',
            unique_together={('ticker', 'date')},
        ),
    ]
