# Generated by Django 5.1.3 on 2025-01-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlfaTrader_App', '0006_portfolio_userstocksbalance_portfoliostocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliostocks',
            name='quantity',
        ),
    ]
