# Generated by Django 5.1.3 on 2025-01-05 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlfaTrader_App', '0007_remove_portfoliostocks_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='modified_at',
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlfaTrader_App.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlfaTrader_App.stocks')),
            ],
        ),
    ]
