# Generated by Django 5.1.3 on 2025-01-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlfaTrader_App', '0008_remove_portfolio_modified_at_userportfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostocks',
            old_name='user_stock_balance',
            new_name='stocks',
        ),
    ]
