# Generated by Django 5.1.3 on 2025-01-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlfaTrader_App', '0009_rename_user_stock_balance_portfoliostocks_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstocksbalance',
            name='avg_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserPortfolio',
        ),
    ]
